workflows:
  release:
    name: iOS → TestFlight
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      groups:
        # Configure in Codemagic UI → Settings → Environment variables
        # APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.nikapps.lottie.developer"
        APP_STORE_APPLE_ID: "6759177169"
        XCODE_SCHEME: "LottieDeveloper"
        TEAM_ID: "LWV5ZRPC43"
      xcode: latest
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: "main"
          include: true
          source: true
    scripts:
      - name: Set up keychain
        script: keychain initialize

      - name: Validate App Store Connect private key format
        script: |
          if [ -z "${APP_STORE_CONNECT_PRIVATE_KEY:-}" ]; then
            echo "APP_STORE_CONNECT_PRIVATE_KEY is not set"
            exit 1
          fi

          if ! printf '%s' "$APP_STORE_CONNECT_PRIVATE_KEY" | grep -q "BEGIN PRIVATE KEY"; then
            echo "APP_STORE_CONNECT_PRIVATE_KEY must contain raw .p8 PEM content, not base64"
            exit 1
          fi

      - name: Fetch iOS signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: keychain add-certificates

      - name: Set up code signing
        script: xcode-project use-profiles --warn-only

      - name: Increment build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID")
          NEW_BUILD=$((LATEST_BUILD + 1))
          echo "Build number: $NEW_BUILD"
          sed -i '' "s/bundleVersion: \"[0-9]*\"/bundleVersion: \"$NEW_BUILD\"/" Package.swift

      - name: Resolve package dependencies
        script: |
          xcodebuild -resolvePackageDependencies \
            -scheme "$XCODE_SCHEME" \
            -clonedSourcePackagesDirPath "$CM_BUILD_DIR/.packages"

      - name: Build iOS archive
        script: |
          xcodebuild archive \
            -scheme "$XCODE_SCHEME" \
            -destination "generic/platform=iOS" \
            -archivePath "$CM_BUILD_DIR/build/ios/LottieDeveloper.xcarchive" \
            -clonedSourcePackagesDirPath "$CM_BUILD_DIR/.packages" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            clean archive

      - name: Export iOS IPA
        script: |
          cat > "$CM_BUILD_DIR/build/ios/exportOptions.plist" <<PLIST
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>${TEAM_ID}</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>uploadSymbols</key>
              <true/>
          </dict>
          </plist>
          PLIST

          xcodebuild -exportArchive \
            -archivePath "$CM_BUILD_DIR/build/ios/LottieDeveloper.xcarchive" \
            -exportOptionsPlist "$CM_BUILD_DIR/build/ios/exportOptions.plist" \
            -exportPath "$CM_BUILD_DIR/build/ios/ipa"

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
        submit_to_app_store: false
